apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubenetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: eventure.dev
      http:
        paths:
          - path: /api/users/?(.*)
            backend:
              serviceName: user-srv
              servicePort: 3000
          - path: /api/organizations/?(.*)
            backend:
              serviceName: organization-srv
              servicePort: 3000
          - path: /api/events/?(.*)
            backend:
              serviceName: event-srv
              servicePort: 3000
          - path: /api/orders/?(.*)
            backend:
              serviceName: order-srv
              servicePort: 3000
          - path: /api/payments/?(.*)
            backend:
              serviceName: payment-srv
              servicePort: 3000
